kind: Deployment
apiVersion: apps/v1
metadata:
  name: resumeio-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resumeio-react
  template:
    metadata:
      labels:
        app: resumeio-react
    spec:
      containers:
      - name: resumeio-react
        image: galudas/resumeio:resumeio-frontend.1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "300m"
          limits:
            memory: "200Mi"
            cpu: "600m"
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: resumeio-react
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: resumeio-react
