apiVersion: apps/v1
kind: Deployment
metadata:
  name: resumeio-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resumeio-model
  template:
    metadata:
      labels:
        app: resumeio-model
    spec:
      containers:
        - name: resumeio-model
          image: galudas/resumeio:resumeio-model.1.0.1
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production
            - name: MONGO_DATASOURCE_URL
              value: mongodb://resumeio-model-db:27017/admin
          imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: resumeio-model
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: resumeio-model
  type: LoadBalancer