apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---

apiVersion: v1
kind: Service
metadata:
  name: resumeio-model-db
spec:
  selector:
    app: resumeio-model-db
  ports:
    - port: 27017
      targetPort: 27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resumeio-model-db
spec:
  selector:
    matchLabels:
      app: resumeio-model-db
  template:
    metadata:
      labels:
        app: resumeio-model-db
    spec:
      containers:
        - name: resumeio-model-db
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
            - name: scripts
              mountPath: ${HOME}/.resumeio/scripts
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: reasumeio-model-db-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reasumeio-model-db-secret
                  key: mongo-root-password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: reasumeio-model-db-secret
                  key: mongo-root-db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: scripts
          hostPath:
            path: /scripts

---

apiVersion: v1
kind: Secret
metadata:
  name: reasumeio-model-db-secret
type: Opaque
data:
  mongo-root-username: cmVzdW1laW9tb2RlbA==
  mongo-root-password: cmVzdW1laW9tb2RlbA==
  mongo-root-db: cmVzdW1laW9tb2RlbA==
