apiVersion: apps/v1
kind: Deployment
metadata:
  name: resumeio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resumeio-api
  template:
    metadata:
      labels:
        app: resumeio-api
    spec:
      containers:
        - name: resumeio-api
          image: galudas/resumeio:resumeio-api.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://resumeio-database:5432/resumeio
            - name: POSTGRES_URL
              value: jdbc:postgres://resumeio-database:5432/resumeio
          imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: resumeio-app
spec:
  selector:
    app: resumeio-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
